development:
  adapter: postgresql 
  encoding: utf8
  reconnect: false
  database: twfynz_development

test:
  adapter: postgresql 
  encoding: utf8
  reconnect: false
  database: twfynz_development

production:
  adapter: postgresql 
  encoding: utf8
  reconnect: false
  database: twfynz_development


